### ISSUE TITLE
Allow arbitrary data 

### ISSUE THREAD

**Issue by grittygrease** [tlswg/tls-exported-authenticator#19]
This is a suggestion from a preliminary formal analysis of the feature by Jonathan Hoyland. In order for a peer to be "jointly-authoritative" over multiple certificates, there needs to be a cryptographic dependency between subsequent EAs. Requiring EAs to be created and validated sequentially without losing any imposes restrictions on their use, and there are applications that don't need compound authentication, so I'm not proposing adding this restriction. However, Jonathan noted that it may be possible to dependencies between different EAs by using the hash of a previous EA using the context_value from the TLS exporter (currently null).

My proposal is to make the context_value user configurable in order to enable applications that want to provide compound authentication claims about. An empty context_value will be used if not provided.

**Comment by martinthomson** [comment]
I think that this is a nice property to get for some cases.  But I'm a little uncomfortable using certificate_request_context to sneak this property in.  I'd prefer an explicit TLS extension.  We could add one to the CertificateRequest.

Depending on who wants the joint authority we could make the extension either empty or include a hash of the last authenticator.  Empty would request that the other side fill the extension in with their recollection of the last authenticator.  That seems more complicated than is ideal, but we have to deal with the possibility that the authenticator is lost in transit, even over TCP (stream resets in h2 are commonplace and those can result in data loss).  Letting either side include the hash makes this flexible.  Each can remember the last authenticator they saw/generated (or hash thereof) and include that on demand.

That loss scenario is why I don't think that we can include anything implicit in the transcript.  Implicit inclusion would mean total loss if an authenticator is dropped.

I think that including the last Finished hash would be sufficient rather than the hash of the authenticator, on the basis that `H(x)` is as good as `H(x||H(x))`.

There's a problem here if you have parallel authenticator requests and reordering of the responses, but I think that the best answer for someone who cares about joint authority is either "sort it out" or "don't do that".

Note that this doesn't work for spontaneous authentication and I think that I'm OK with that.

**Comment by grittygrease** [comment]
Closing this issue in favor of proposing a mechanism based on extensions.
