### ISSUE TITLE
This would be easier and maybe even safer with a CertificateRequest

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls-exported-authenticator#5]
As an "API", a CertificateRequest isn't ideal, but it allows us to codify a bunch of things.  That includes choices about certificates for the purposes of satisfying signature_schemes, and it might also allow for other improvements to be added.

I'm tempted to make the provision of a CertificateRequest mandatory.  You could do that by including the request in the hash that is input to Finished.  On the other hand, ensuring that all inputs that are used to select the final message are covered by a hash is fairly tempting.

The API need not explicitly take a CertificateRequest.  It could even say that implementations can construct a CertificateRequest with no extensions when spontaneously advertising certificate.  But looking at the HTTP and the way that is going, it might help that use case to have the certainty that having the request included under the hash.

**Comment by grittygrease** [comment]
In this proposal, the input to the "authenticate" API would take a CertificateRequest object rather than just a certificate_request_context and the "validate" API would take an additional CertificateRequest value, correct?

The problem with this proposal is that it prevents an Exported Authenticator to be used for different CertificateRequests. @MikeBishop noted that there is a use case from HTTP/2 secondary certificates in which the server wants to provide the same CERTIFICATE frame for multiple CERTIFICATE_REQUEST frames (each with a different set of Certificate Request extensions, specifically SNI). This additional requirement to include the CertificateRequest to the "validate" API strongly binds the authenticator to the request, precluding this possibility.

Strong binding between request and response is a nice feature to have, but because the certificate selection choice is explicitly not part of this spec I'm not sure this is the right place to put it.

**Comment by martinthomson** [comment]
> the "validate" API would take an additional CertificateRequest value, correct?

Yes.  Though I imagine that you could build a lighter-weight API that only took the certificate_request_context (or nothing in the case of "validate") and the API would construct the CertificateRequest from the information it has.  That is, it doesn't make the CertificateRequest mandatory.

For the N-to-1 case in the h2 draft, if the same certificate fits multiple requests, couldn't the USE_CERTIFICATE frame be used to identify a certificate?

That is, if a client asks for foo.example.com and bar.example.com, then the server can answer one with a certificate that has subjectAltName listing both, deny the other request, and then point at both as necessary with USE_CERTIFICATE.

**Comment by grittygrease** [comment]
In the N-to-1 case, it depends on whether the SNI was included in the calculation of the Exported Authenticator or not. If a stream for foo.example.com is pointed to a CERTIFICATE frame for bar.example.com using USE_CERTIFICATE, then it needs a way to reconstruct the CertificateRequest value correctly because its CERTIFICATE_REQUEST will contain the wrong set of extensions in the CertificateRequest. I guess this complication could be avoided by removing any SNI extensions when creating the Exported Authenticator -- that seems like extra complexity for little gain. Alternatively, the CertificateRequest could be fully synthetic, but then what's the point of adding it to the Exported Authenticator at all vs. just a certificate_request_context.

**Comment by martinthomson** [comment]
Once CERTIFICATE is processed and validated (using the CERTIFICATE_REQUEST that caused it to be created), then it can just be used.  USE_CERTIFICATE is a pointer to the certificate, not to the transaction.

**Comment by grittygrease** [comment]
So how do you correlate a CERTIFICATE_REQUEST with a CERTIFICATE frame? Say the client sends three CERTIFICATE_REQUEST frames, the first two are on the current certificate. The server will send back two CERTIFICATE frames, one for the first request (to be used for all CERTIFICATE_NEEDED frames that are referenced by the first two CERTIFICATE_REQUEST frames), and one for the third CERTIFICATE_REQUEST. How does the client know which CERTIFICATE frame is tied to which CERTIFICATE_REQUEST? There are no identifiers to bind requests to responses, so it will have to be trial and error. Throw in spontaneous CERTIFICATES and you'll need to do more trial and error.

Linking Req-ID and Cert-ID could potentially solve this, but it seems messy without a direct association.

**Comment by grittygrease** [comment]
I agree that this makes a lot of sense. It’s especially useful for providing a way to let the TLS library decide which extensions to include in the exported authenticator and which signature schemes to use, rather than leaving these decisions up to the application later (which is what this draft currently does). I just don’t think this works with the current additional certs draft, so maybe the change needs to happen there.

**Comment by grittygrease** [comment]
Correction: maybe a change needs to happen in the other draft to make it compatible with this change.

**Comment by martinthomson** [comment]
Here's how I think that this could work:

CERTIFICATE_REQUEST: includes a CertificateRequest message, which includes certificate_request_context

CERTIFICATE: includes a certificate-id and an exported authenticator (which includes the certificate_request_context in the Certificate message that is used to correlate with the  CERTIFICATE_REQUEST).

CERTIFICATE_NEEDED: includes a certificate_request_context to identify the CERTIFICATE_REQUEST.

USE_CERTIFICATE: uses certificate-id to identify a CERTIFICATE to use.

I'm thinking that we should make certificate-id longer (or variable-length even) just to keep things flexible.  It might be nice to use the same value for certificate-id and certificate_request_context, but the two are logically orthogonal concepts.

This is almost what we have already.

**Comment by grittygrease** [comment]
The issue I see with this is that we will need two APIs, one to extract the certificate_request_context from the Delagated Credential, and another to validate the authenticator once the correct CertificateRequest has been found. Making certificate_request_context and certificate-id match would remove the need for the first API.

**Comment by martinthomson** [comment]
Yeah, that does suck.  The problem is that we split the two identifiers so that certificate-id was entirely driven by the peer that sends CERTIFICATE.  If the two identifiers are merged, we need some sort of anti-collision mechanism.

**Comment by grittygrease** [comment]
We could use two identifiers and Just include them both where possible.

**Comment by grittygrease** [comment]
Another potential issue with this change: if we want to keep the same logic from TLS about extensions (a Certificate extension can only be present if it was present in the CertificateRequest), and one party wants to create a spontaneous CERTIFICATE with, say, an OCSP response, then an OCSP extension needs to be added to the synthetic CertificateRequest the verifier needs to know how to construct it. For spontaneous server auth, the extensions could maybe be taken to be the extensions in the initial ClientHello message of the connection, and for client auth it could be empty. Neither of these seem like good solutions.

**Comment by grittygrease** [comment]
Ok, after some serious thought and working through the implementation scenarios, I think I agree with this. There will have to be substantial changes to the draft, but I think that the end result will make the certificate and extension selection logic more well-defined and result in fewer bugs. The spontaneous auth functionality in secondary certificates will have to use a synthetic CertificateRequest, which should be fine except in the case of spontaneous client auth, where the client has no way of knowing which signature_schemes the server supports. This is fine because the spontaneous client auth option does not have an explicit use case. Certificate selection can be based on the set of extensions present in the client hello with additional constraints (OID, CA) from the CertificateRequest for client auth.

We'll have to do the following:
* define a new API for creating an "exported authenticator request" which will look like a TLS 1.3 CertificateRequest message, taking SNI for server auth requests and optionally OID Filter & CA for client auth requests
* add logic to incorporate the exported authenticator request into the exported authenticator transcript to be signed
* modify the exported authenticator creation API to take an exported authenticator request and set of certificates, rather than a certificate_request_context and a single certificate
* let the TLS library select the certificate based on the extensions from the incoming certificate request and the connection's client hello message, if an SNI extension is included (server auth requests only), this should be used in certificate selection instead of the SNI from the client hello
* the rules for which extensions should be included should follow those from TLS 1.3: only include extensions if they are part of the ClientHello and additionally respect the OID Filter, Certificate Authorities, and SignatureScheme extensions
* allow server exported authenticator creation with a "synthetic" certificate request that doesn't have extensions for the spontaneous auth case
* modify the exported authenticator verification API to take an exported authenticator request instead of a certificate_request_context
* add an API to extract the certificate_request_context from an exported authenticator for the sender to look up the matching exported authenticator request, or to construct the synthetic exported authenticator request needed to validate the exported authenticator

How does this sound, @martinthomson?

**Comment by grittygrease** [comment]
The only other wrinkle I see is SNI. In TLS, we don't define SNI as an extension for CertificateRequest. I propose we allow clients to add an SNI extension into the exported authenticator request, and allow that to override the client hello's SNI on the server side for certificate selection.

**Comment by martinthomson** [comment]
This seems OK.  I think that we need to make it clear that extensions in a CertificateRequest completely replace extensions from the ClientHello.  In particular, you need to specify signature_algorithms if you provide a CertificateRequest.  That makes the logic an OR here.

I think that we can allow a CertificateRequest to be optional rather than synthesize one.  That is, the transcript will omit the request (and the extensions call back to the handshake).

What did you decide about spontaneous client authentication?

We need to make a special carve-out for SNI here.  I think that's OK.

I don't think that you have to specify the certificate selection logic.

**Comment by MikeBishop** [comment]
We don't have a use case for spontaneous client other than clients trying to save a round-trip when they expect the server to ask. That seems like an acceptable loss.

On the whole, I think this is about right. I was going to say that the synthetic request should have the extensions of the ClientHello, not "no extensions," but even that's not quite right, since it should omit SNI from that. Just letting spontaneous certs omit the request seems reasonable. 

I half wonder if a peer ought to generate a very broad Request that describes what it can validate (signature algorithms, cached info, etc.) but not what it's looking for, and let that be the request that's used for all spontaneous certs. But that seems needless overhead when it's not going to be used, and waiting for an indication of support burns a round-trip instead.
